services:
  #  api:
  #    build: .
  #    ports:
  #      - '8080:8080'
  #    restart: always
  #    environment:
  #      MONGODB_URL: mongodb://dev:passdev@mongo:27017/
  #    volumes:
  #      - .:/src
  #    depends_on:
  #      - mongo


  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: passdev
      MONGO_INITDB_DATABASE: coffee-chooser
    ports:
      - '27017:27017'
    volumes:
      - ./scripts/mongo-init.js://docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - chooser-cafe-network
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dev
      ME_CONFIG_MONGODB_ADMINPASSWORD: passdev
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://dev:passdev@mongo:27017/
    networks:
      - chooser-cafe-network
#  mindsdb:
#    image: mindsdb/mindsdb:lightwood
#    restart: always
#    ports:
#      - "47334:47334" # Porta do MindsDB
#    environment:
#      MINDSDB_CONFIG_DEFAULT_STORAGE: 'mongodb://dev:passdev@mongo:27017'
#    depends_on:
#      - mongo
#    networks:
#      - chooser-cafe-network


networks:
  chooser-cafe-network:
    driver: bridge

