version: '3'

services:
#  api:
#    build: .
#    ports:
#      - '8080:8080'
#    restart: always
#    environment:
#      MONGODB_URL: mongodb://root:root!@mongo:27017/
#    volumes:
#      - .:/src
#    depends_on:
#      - mongo


  mongo:
    restart: always
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: passdev
    ports:
      - '27017:27017'
    volumes:
      - ./scripts/mongo-init.js:/scripts/mongo-init.js:ro
      - ./Docker/Volumes/MongoDB:/data/db
    networks:
      - chooser-cafe-network
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dev
      ME_CONFIG_MONGODB_ADMINPASSWORD: passdev
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://dev:passdev@mongo:27017/
    networks:
      - chooser-cafe-network

networks:
  chooser-cafe-network:
    driver: bridge

